### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by inihaekal** [try-catch-dev/BotWhatsapp#1]
result.data = response?.data?.choices?.[0].text || 'Aku gak tau';
                                       ^

SyntaxError: Unexpected token '.'

**Comment by try-catch-dev** [comment]
pake node js versi berapa ya?

coba tambahkan tanda tanya sebelum text.
result.data = response.data?.choices?.[0]?.text || 'Aku gak tau';

dan pastikan file config sudah di ubah api key nya
